### PR TITLE
Pull request with changes by Zearin plus some tweaks

### PR DESCRIPTION
**Pull request by greduan**
Hey @balupton. I made this specifically a pull request because @Zearin made some significant changes to some text and I want to make sure you don't disagree or see anything wrong with it. :)

These are changes that @Zearin made in #12.

Ignoring small changes and stuff like typos, names etc., do you see anything wrong with what @Zearin said? Mainly about reasons to use CoffeeScript instead of JS, so from around line 183 to line 207.

The rest I've checked and I believe is OK, but if you find anything point it out so I can fix it. :)

### CODE REVIEW

**Comment by balupton** [comment]
@c-j-s would you like to review this and merge?

**Comment by c-j-s** [comment]
Actually, I'm no longer using Docpad (I'm working with a friend on our own custom build framework for static sites 'cause hacking) so it's probably best to get someone who's going to be around moving forward to review and merge this.

**Comment by balupton** [comment]
No worries @c-j-s. Are either @hal-gh or @zearin still around?

**Comment by superclarkk** [comment]
@balupton Sorry I've been so quiet. Being realistic, I won't have time to contribute to this project, albeit a fantastic project. Apologies.  Thanks to you and your crew for including me in the past.

**Comment by hal-gh** [comment]
@balupton Sorry I've been so quiet. Being realistic, I won't have time to contribute to this project, albeit a fantastic project. Apologies. Thanks to you and your crew for including me in the past.

**Comment by greduan** [comment]
Closing this, just visited https://github.com/pulls and noticed there's this PR, from way back in 2014. x|

**Pull request closed without merging**
